### ISSUE TITLE
Missing copyright statements in file that uses GPL-licensed code

### ISSUE THREAD

**Issue by gonzalo-bulnes** [jamke/qubes-completion#7]
## Overview

While the intent seems clear, the current use of code from the bash-completion project doesn't quite follow the license rules about re-use. (In a gist: keep the copyright statements, add your own to any file that contains a significant piece of code that someone else contributed to writing. _This doesn't pretend to be legal speech, I am not a lawyer._)

Specifically `src/qubes-completion.sh` is missing the copyright statements that correspond to the piece of code derived from bash-completion.

The `THIRDPARTY` file contains a disclaimer about the origin of the code. However, that is not quite sufficient to fulfill the license obligations. (Standalone disclaimers like that are generally used for libraries or assets that are redistributed unmodified, but that is not the case here.)

## Why bother?

I want this project to thrive, and I think all authors should get proper credit for their work. It turns out that's exactly what the copyright rules surrounding licensed do, in an unambiguous manner. The same rules will ensure that projects derived from this one give proper credit to its author(s). :slightly_smiling_face:

## Fix (option 1)

In this case, the situation is fairly straightforward and the fix easy:

- `src/qubes-completion.sh` contains code derived from code that was released under the `GPL-2.0-or-later` (according to the `THIRDPARTY` file)
- that the copyright headers that are included in `THIRDPARTY` should appear in `src/qubes-completion.sh`
- once that's done, the `THIRDPARTY` file becomes redundant

## Fix (alternative)

If identifying specifically the piece of code that's derived from bash-completion is desired, that function could be extracted to a separate file, that would contains all the copyright statements.

At release time, the release artifact could be created by concatenating all source files. (That does add some tooling to the repo, for example a `Makefile`, which may or not be desirable.)

**Comment by jamke** [comment]
I completely rewrote this small third-party block of code. 
New implementation is: 
* smaller, 
* cleaner, 
* more consistent with the whole project,
* and now there is no need to suppress `shellcheck` errors and warnings for this block of code.

I consider the issue to be solved. Feel free to write any comments in the ticket anyway.
