### ISSUE TITLE
BATS tools could be included to make testing setup easier

### ISSUE THREAD

**Issue by gonzalo-bulnes** [jamke/qubes-completion#9]
## Overview

- Currently, testing currently depends on three tools provided by the BATS framework ([docs](https://github.com/jamke/qubes-completion/tree/v1.0.1#tests)):
  - bats-assert ([`CC0-1.0`](https://github.com/bats-core/bats-assert/blob/v2.1.0/LICENSE))
  - bats-file ([`CC0-1.0`](https://github.com/bats-core/bats-file/blob/v0.3.0/LICENSE))
  - bats-support ([`CC0-1.0`](https://github.com/bats-core/bats-support/blob/v0.3.0/LICENSE))
- Those need to be present in a specific path of the project before the existing test suite can be executed (`test/test_helper/bats-*`).
- Given their license, they could be included in the project

## Why

- Remove the need for would-be contributors to fetch and add them themselves
- Open the possibility of running the test suite in a GitHub Action (I'll open a separate issue to discuss that)

### Git submodules

**Pros**: Adding the three BATS repositories as git _submodules_ makes it easier to keep track of which versions of the tools are currently in use, and eventually to update them.
**Cons**: However, it requires being aware of submodules when pulling the repository. (Mitigation: a note can be added to the **Tests** section of the documentation.) 

### Copies

A simple copy of the BATS tools can also be included with the project.

**Pros**: Simple. Those become part of the project like any other file, and no special setup is needed before tests can be run.
**Cons**: It is less obvious which version is used (which may or not matter).

**Comment by jamke** [comment]
NOTE: I compared speed of running tests by `bats` as a package and as a github repo and it is almost the same.
